### ISSUE TITLE
What data structure is the data stored in?

### ISSUE THREAD

**Issue by wcdeich4** [chinedufn/load-wavefront-obj#1]
Hi. More of a question than an issue - after the data is read from the file, what kind of data structure(s) is it stored in?

**Comment by chinedufn** [comment]
Hey @wcdeich4 

So this isn't well documented yet, but after parsing the model we store the relevant data in a [JSON object](https://github.com/chinedufn/wavefront-obj-parser#returned-object). The JSON object holds the data about a vertex's positions, a vertex's normal and a vertex's texture coordinates.

After that we [buffer the data](https://github.com/chinedufn/load-wavefront-obj/blob/9df5046f30b5769e8e62b587030b3a4d9aa357b2/src/load-wavefront-obj.js#L19-L22) so that the GPU can later access it whenever we want to draw.

You can get a (somewhat) more complete picture by taking a look at the [wavefront-obj-parser demo](https://github.com/chinedufn/wavefront-obj-parser/tree/464b0c948e01848383b71aa6db557635b8bd473e/demo). Here's [how to run that demo locally](https://github.com/chinedufn/wavefront-obj-parser/tree/464b0c948e01848383b71aa6db557635b8bd473e#running-the-demo-locally).

---

Hopefully that helps? Let me know if I missed anything!
